import {
  bulkArchiveAdminNotifications,
  bulkMarkAdminNotificationsAsRead,
  bulkRestoreAdminNotifications,
  createBookingCreatedAdminNotifications,
  createBookingSquadsUpdatedAdminNotifications,
  createBookingStatusChangedAdminNotifications,
  getAdminNotificationOverview,
  getAdminNotificationRules,
  getAdminNotificationSummary,
  getAdminNotifications,
  updateAdminNotificationPreferences,
  updateAdminNotificationRules,
  markAdminNotificationAsRead,
  markAllAdminNotificationsAsRead,
} from "@/features/admin/lib/server/admin-notifications";

export {
  bulkArchiveAdminNotifications,
  bulkMarkAdminNotificationsAsRead,
  bulkRestoreAdminNotifications,
  createBookingCreatedAdminNotifications,
  createBookingSquadsUpdatedAdminNotifications,
  createBookingStatusChangedAdminNotifications,
  getAdminNotificationOverview,
  getAdminNotificationRules,
  getAdminNotificationSummary,
  getAdminNotifications,
  updateAdminNotificationPreferences,
  updateAdminNotificationRules,
  markAdminNotificationAsRead,
  markAllAdminNotificationsAsRead,
};
